import Head from 'next/head'
import { useState } from 'react'
import { CardIcon } from '../components/cardIcon'

export default function Home() {
  const [acctName, setAcctName] = useState('')
  const [acctNo, setAcctNo] = useState('')
  const [month, setMonth] = useState('')
  const [year, setYear] = useState('')
  const [cvv, setCvv] = useState('')
  const [errorMsg, setErrorMsg] = useState('')

  function handleSubmit(e) {
    e.preventDefault()

    if(!acctName || !acctNo || !year || !!cvv ||!month ) {
      setErrorMsg('Please Input all data before submitting!')
      alert(errorMsg)
    }
  }

  return (
    <div>
      <Head>
        <title>Interactive Card Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen w-full flex flex-col md:flex-row '>
        <div className='md:flex-1 bg-main relative'>
            <div className='card-front flex flex-col justify-between py-4 px-3 absolute top-10 left-10 h-[147px] md:h-[245px] w-[268.2px] md:w-[447px] rounded-lg '>
                <CardIcon />

                <div className='text-white'>
                  <h2 className='text-lg md:text-3xl mb-3 md:mb-6 font-semibold '>
                    {
                      acctNo ?  `${acctNo.slice(0, 4)} ${acctNo.slice(4, 8)} ${acctNo.slice(8, 12)} ${acctNo.slice(12, 16)}` : '0000 0000 0000 0000'
                    }
                  </h2>
                  <div className='flex justify-between items-center font-medium text-md md:text-lg'>
                    <p>
                      {
                        acctName ? acctName.toUpperCase() : 'JANE APPLESEED'  
                      }
                    </p>
                    <p>
                      {
                        month ? month.slice(0, 2) : '01'
                      } {' / '}
                      {
                        year? year.slice(0, 2) : '22'
                      }
                    </p>
                  </div>
                </div>
            </div>

            <div className='card-back absolute top-[11rem] md:top-1/2 left-24 h-[147px] md:h-[245px] w-[268.2px] md:w-[447px] rounded-lg '>
              <div className='text-right mt-[6.5rem] mr-14 text-xl italic '>
                 {
                  cvv ? cvv.slice(0, 3) : '000'
                 }
              </div>
            </div>
        </div>
        <div className='mt-32 md:mt-0 mb-8 md:mb-0 md:flex-[2.5] h-auto flex items-center justify-center'>
          <form>
            <label className='uppercase font-medium text-xl inline-block' htmlFor="">cardholder name</label> <br />
            <input 
              type="text"
              value={acctName}
              placeholder='e.g Jane Appleseed' 
              className='border w-full py-2 px-1 rounded-md' 
              onChange={(e) => setAcctName(e.target.value)}
              maxLength={18}
            /> 
            <br />
            <label className='uppercase font-medium text-xl inline-block mt-4' htmlFor="">card number</label> <br />
            <input 
              type="number"
              min={0}
              maxLength={16} 
              placeholder='1234 5678 9123 0000' 
              className='border w-full py-2 px-1 rounded-md'
              value={acctNo}
              onChange={(e) => setAcctNo(e.target.value)} 
            />
            <div className='flex space-x-8 mt-4'>
              <div>
                <label className='uppercase font-medium text-xl' htmlFor="">EXP. DATE (MM/YY) </label> <br />
                <input 
                  type="number" 
                  className='w-16 py-2 px-1 rounded-md border'
                  placeholder='MM' 
                  maxLength={2} 
                  max={12} 
                  min={1}  
                  value={month}
                  onChange={(e) => setMonth(e.target.value)}
                />{' '} / {' '}
                <input 
                  type="number" 
                  className='w-16 py-2 px-1 rounded-md border'
                  placeholder='YY' 
                  maxLength={2} 
                  min={22}
                  value={year}
                  onChange={(e) => setYear(e.target.value)}
                />
              </div>
              <div>
                <label className='uppercase font-medium text-xl' htmlFor="">CVC</label> <br />
                <input 
                  type="number" 
                  className='w-[5.5rem] py-2 px-1 rounded-md border' 
                  placeholder='e.g 123' 
                  maxLength={3}
                  value={cvv}
                  onChange={(e) => setCvv(e.target.value)} 
                />
              </div>
            </div>
            <input 
              type="submit" 
              value="Confirm"
              onClick={handleSubmit} 
              className='bg-[#610696] mt-8 w-full text-white rounded-lg font-semibold py-2 cursor-pointer ' 
            />
          </form>
        </div>
      </main>

      
    </div>
  )
}
